---

- name: Update all packages to their latest version
  dnf:
    name: "*"
    state: latest

- name: Installing EPEL repositories
  yum:
    name: "epel-release"
    state: latest

- name: Installing DNF core plugins
  yum:
    name: "dnf-plugins-core"
    state: latest

- name: Enabling powertools repository (Centos8)
  command: yum config-manager --set-enabled powertools
  args:
    warn: no
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "8"
  notify: yum-clean-metadata

- name: Enabling CodeReady builder repository (RHEL8)
  command: subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms
  args:
    warn: no
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"
    - ansible_facts['architecture'] == "x86_64"
  notify: yum-clean-metadata


  

